Extract SignallingWebServer matchmaker and player classes
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #120
Opened 2023-02-23 15:12 UTC by gunsha

Extract SignallingWebServer matchmaker socket into it's own class to help make the code more readable
relates to #10

2023-02-23 15:13 UTC, gunsha commented
@lukehb rebased the repo and signed the commit

2023-02-24 01:14 UTC, lukehb commented
@Belchy06 This bodes well for the refactor we intend to do in 5.3 anyway. Can I get you to review and QA against multi-streamer and SFU feature set to ensure no regressions?

2023-02-24 12:48 UTC, gunsha commented
@lukehb @Belchy06 do you guys have any automation test set for this or is all done manually?

2023-02-25 02:19 UTC, Belchy06 commented
Unfortunately it's all still manual QA but automated tests are planned

2023-02-27 01:57 UTC, lukehb commented
@MWillWallT If Will is swamped, can you also QA this PR to ensure things are still working, particularly multi-streamer and SFU feature set.

2023-03-02 01:34 UTC, Belchy06 requested changes

2023-03-02 01:34 UTC, Belchy06 commented on SignallingWebServer/cirrus.js
> +const WebSocket = require('ws');
Need to either remove this line or L317 as there's now 2 definitions

2023-03-02 01:34 UTC, Belchy06 commented on SignallingWebServer/modules/player.js
> +		if (!streamers.has(streamerId)) {
The player class doesn't know about this variable which is global to cirrus.js

2023-03-02 01:34 UTC, Belchy06 commented on SignallingWebServer/modules/player.js
> +			logOutgoing(this.streamerId, msg);
logOutgoing will undefined as that method is defined in cirrus.js

2023-03-02 01:34 UTC, Belchy06 commented on SignallingWebServer/modules/matchmaker.js
> +	#sendMessage(message){
Probably don't want our methods containing special characters

2023-03-02 23:00 UTC, gunsha commented on SignallingWebServer/modules/matchmaker.js
> +	#sendMessage(message){
any reason for this? that's just the way of declaring private members according to [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/Private_class_fields)

2023-03-02 23:57 UTC, lukehb commented
@gunsha Due to other changes landing, this PR has conflicts that need to be resolved now.

2023-03-03 00:25 UTC, gunsha commented
@lukehb pushed some changes to resolve the conflict

2023-03-03 00:29 UTC, Belchy06 commented
Still getting conflicts. You'll most likely just need to bring your fork up to date as it's 34 commits behind. Once your fork is synced you can rebase your changes and be good to go from there.

2023-03-03 00:39 UTC, gunsha commented
@Belchy06 @lukehb repo is synced now 👌

2023-03-06 01:34 UTC, Belchy06 reviewed
These changes are non-functional and actually crash the signalling server when a player connects.

Do you have the ability to test these changes against a running Pixel Streaming application? If so, I'd implore you to try running the updated signalling server and testing both player and SFU connection.

2023-03-06 01:34 UTC, Belchy06 commented on SignallingWebServer/package.json
> +    "jest": "^29.4.3"
Can you just change this to be `"jest": "27.5.1"`. Version 29 requires >= node 16.10 but we explicitly use 16.4.2 in the install scripts.

I've verified testing the suite with v27.5.1 still passes.

2023-03-07 12:29 UTC, gunsha commented on SignallingWebServer/package.json
> +    "jest": "^29.4.3"
changed the jest version

2023-03-07 12:30 UTC, gunsha commented
@Belchy06 tested against SFU and browser, now it's working

2023-03-15 23:49 UTC, lukehb commented
@Belchy06 or @MWillWallT to test this PR - particularly with multi-streamer feature and SFU

2023-03-16 07:03 UTC, Belchy06 commented on SignallingWebServer/cirrus.js
> +	matchmaker?.setStreamerReadyState(streamer.readyState);
You're attempting to use the streamer here but it isn't declared until line 405. This causes a crash in its current state

2023-03-16 07:05 UTC, Belchy06 commented
Unfortunately, due to the sections this PR is attempting to modify, it needs a very in depth QA process.

We've recently moved the Unreal Engine docs for Pixel Streaming to this repo. I'd suggest trying to stream with a matchmaker as well, the docs should explain how to set that up. 

Let us know if you need any help.

Cheers

2023-03-20 01:05 UTC, lukehb commented
@gunsha In addition to @Belchy06  comment, master has changed again due to fixing some security issues last week. I will need you to resolve conflicts and address @Belchy06  comments before I can merge this one.

As @Belchy06 said, let us know if you need any help from our side. This change is a good one and I would like to get it merged assuming we can ensure everything is still working as before.

2023-03-20 01:39 UTC, gunsha commented
Hey @lukehb I'll be checking this tomorrow, I should be able to run the whole thing completely, I'll let you know guys if I need anything from your side 👌

2023-03-21 14:01 UTC, gunsha commented
@lukehb tested again with and without matchmaker and seems to be working fine, couldn't try again with SFU, moved to an M2 mac an seems that the mediasoup_prebuilt is not working

2023-03-22 06:01 UTC, lukehb commented
@Belchy06 or @MWillWallT Can either of you test this on @gunsha behalf.

@gunsha I see there are once again conflicts that need to be resolved.

2023-03-22 12:51 UTC, gunsha commented
@lukehb merged with master

2023-04-13 01:48 UTC, Belchy06 commented
This one looks good to go @gunsha.

We're currently winding down active development of the master branch in preparation for the 5.2 launch, meaning we're only merging critical bug fixes.

We'll open back up to features once 5.2 has launched.

2023-07-17 00:36 UTC, closed without merging

2023-07-17 00:36 UTC, Belchy06 commented
Heya @gunsha,

This has been cherry picked as part of a larger commit.

Your changes can be seen here: https://github.com/EpicGames/PixelStreamingInfrastructure/commit/c89193e46d9071de40507f0a522e34b0b6c7f462

Thank you!