Api support for UE communication
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #132
Opened 2023-03-01 12:45 UTC by hmuurine

# Summary

Adds support for browser <-> UE communication through the API:
- `emitUIInteraction(data: object | string)`: sends arbitrary data as an `UIInteraction` message
- `emitConsoleCommand(command: string)`: sends a console command -- only allowed if the UE app has been started with `-AllowPixelStreamingCommands` command line argument
- `addResponseEventListener(name, funct)` / `removeResponseEventListener(name)`: register/remove a listener that is triggered when receiving UE -> browser messages

# Test plan

## Browser <-> UE
- Modified UE Pixel Streaming application to do the following:
   - Monitors for any incoming browser -> UE messages that contain the string `EchoBack`
   - If one received, send back a response with content `EchoResponse: $originalMessage`
![blueprint](https://user-images.githubusercontent.com/8232602/222142069-21e428ea-2594-41ae-b01b-b7cb1f8aa4f4.png)
- Modified `uiless.ts` to do the following:
   - Sends a `UIInteraction` message starting with `EchoBack` 10 seconds after page has been opened
   - Logs any responses received from UE
![Screenshot 2023-03-01 at 13 55 30](https://user-images.githubusercontent.com/8232602/222142310-f3b49bf8-64dc-4c3d-ab45-0216eaf4bb8f.png)
- Started uiless.html and waited for 10 seconds
- Verified that the browser -> UE and UE -> browser messages were both logged, ensuring that communication works both ways
![Screenshot 2023-03-01 at 13 42 55](https://user-images.githubusercontent.com/8232602/222142437-2ba0ef45-b26a-46eb-9daf-9ccb6b071801.png)

## Console commands
- Started a Pixel Streaming UE app with command line parameter `-AllowPixelStreamingCommands`
- Added some code to `uiless.ts` to toggle FPS counter 10 seconds after initialization:
```
setTimeout(() => {
	pixelStreaming.emitConsoleCommand("stat fps");
}, 10000);
```
- Opened `uiless.html`, waited for 10 seconds, and verified that FPS counter was enabled
![Screenshot 2023-02-28 at 9 28 26](https://user-images.githubusercontent.com/8232602/222142919-ea9054d2-0cc5-4ce5-b8b1-a0f9313fff84.png)
- Repeated the test with `-AllowPixelStreamingCommands` command line arg disabled
- Verified that FPS counter was not enabled after 10 seconds, since the console command was rejected

2023-03-01 12:49 UTC, hmuurine commented on Frontend/library/src/UeInstanceMessage/SendDescriptorController.ts
> +    sendDescriptor(messageType: string, descriptor: object | string) {
Supporting `object | string` to match what is promised in https://docs.unrealengine.com/5.1/en-US/customizing-the-player-web-page-in-unreal-engine/ 
> When you call the emitUIInteraction function, you can pass it a single string or JavaScript object.

2023-03-02 01:09 UTC, lukehb requested changes

2023-03-02 01:09 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +
There is also another option we may as well expose here, which is `emitCommand(descriptor)` that calls 

```ts
this.sendDescriptorController.emitCommand(descriptor);
```

This is used for inbuilt commands we always accept (like changing EncoderMinQP for example) and newly in 5.2 we also expose on the C++ side a way for users to bind custom command messages so we should also expose a way for users to send these using our new library.

2023-03-02 01:09 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +
For the test plan, on the C++ side you should be able to something like this to set a custom handler:

```C++
IPixelStreamingModule& PSModule = IPixelStreamingModule::Get();
PsModule.GetStreamer(PSModule.GetDefaultStreamerID())->GetInputHandler()->SetCommandHandler(YourHandler)`
```

Or you can test using one of the existing in-built commands like `Encoder.MinQP`

2023-03-02 06:44 UTC, hmuurine commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +
Sounds good, if it's ok to expose this more capable interface. I'll make the changes 👍

2023-03-02 07:16 UTC, hmuurine commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +
Removed `emitConsoleCommand` and added `emitCommand` in commit https://github.com/EpicGames/PixelStreamingInfrastructure/pull/132/commits/70c14a5fc6b78f6fc24ca534dd4c08a0125c189d

2023-03-02 23:08 UTC, lukehb approved these changes

2023-03-02 23:11 UTC, lukehb requested changes

2023-03-02 23:11 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.ts
> +
@hmuurine Sorry to be a bother on this one. But on further consideration, we should have both `emitCommand` and `emitConsoleCommand`. Mostly keeply the latter to match existing 5.1 documentation.

2023-03-03 06:46 UTC, hmuurine commented on Frontend/library/src/PixelStreaming/PixelStreaming.ts
> +
No worries, restored the previous implementation and now both are there. 👍

2023-03-06 01:01 UTC, lukehb approved these changes
lgtm!

2023-03-06 01:01 UTC, merged