Customize styles through UI API
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #133
Opened 2023-03-01 15:39 UTC by hmuurine

# Summary

Added code that allows the users to customize styles via the UI API.

-   No longer applying styles automatically in constructor. Need to call `applyStyles()`
-    Developers can give custom overriding CSS styles as optional parameters in `new PixelStreamingApplicationStyle()` constructor
-    Moved light/dark mode palette applying code from `Application` to `PixelStreamingApplicationStyle` to keep all the style related code in a single place
- `Application` now exposes an optional `onUpdateColors` callback that is called when light/dark mode is toggled. The style class hooks into this to apply styles on mode change
-    Developers can give light/dark mode palette as an optional parameter in `new PixelStreamingApplicationStyle()` constructor to override the default colors

# Test plan

-    Ran the frontend without any style overrides, and verified that the default styles were applied
![Screenshot 2023-03-01 at 17 12 42](https://user-images.githubusercontent.com/8232602/222186531-172ef1d0-d793-437f-b67e-2992a80aad4d.png)
-    Toggled between light/dark mode and verified that the styles were applied
![Screenshot 2023-03-01 at 17 12 51](https://user-images.githubusercontent.com/8232602/222186590-1ee4d090-7c84-4c23-904f-620708bb4d2a.png)
-    Modified player.ts to apply custom styles and verified that the styles were applied
![Screenshot 2023-03-01 at 17 17 02](https://user-images.githubusercontent.com/8232602/222186653-f076c13a-9bd4-4e4b-bbd8-ec84b240321a.png)
![Screenshot 2023-03-01 at 17 17 32](https://user-images.githubusercontent.com/8232602/222186678-d39fb260-4ecf-46f1-9aad-179fe14d5441.png)
-    Modified player.ts to set a custom light/dark mode palette and verified that the styles were applied on toggling color mode
![Screenshot 2023-03-01 at 17 20 57](https://user-images.githubusercontent.com/8232602/222186774-44757ba3-57b8-4f19-af60-41fcaedd64cc.png)
![Screenshot 2023-03-01 at 17 20 19](https://user-images.githubusercontent.com/8232602/222186810-72e9be1e-c771-4bf7-b9c7-3fc64fd2eb83.png)
![Screenshot 2023-03-01 at 17 20 28](https://user-images.githubusercontent.com/8232602/222186833-c6bd8cff-a9cf-484f-b199-3061e04e9b1a.png)

2023-03-01 16:21 UTC, hmuurine commented on Frontend/ui-library/src/Styles/PixelStreamingApplicationStyles.ts
>      };
The style diff looks a bit strange but there are zero changes to the styles. Just removed the `global` wrapper which is applied below when combining the default styles with the overrides. The changes above are caused by decreased indentation & prettier auto-formatting.

2023-03-01 23:32 UTC, lukehb commented
CC @Belchy06 for vis

2023-03-02 00:03 UTC, lukehb requested changes

2023-03-02 00:03 UTC, lukehb commented on Frontend/ui-library/src/Application/Application.ts
> +    onUpdateColors?: (isLightMode: boolean) => void;
I know this PR is just following the existing naming convention of `updateColors`; however, given it is now exposed, I propose we rename that method and all the related methods to `setColorMode(isLightMode: boolean)` so we end up with `onColorModeChanged` or similar. Wdyt @hmuurine @Belchy06 ?

More generally though, I am happy with the changes.

2023-03-02 06:27 UTC, hmuurine commented on Frontend/ui-library/src/Application/Application.ts
> +    onUpdateColors?: (isLightMode: boolean) => void;
Good idea! The new name describes better what it does. I updated the names in commit https://github.com/EpicGames/PixelStreamingInfrastructure/pull/133/commits/5c98f21073b0d54668ee5add95302d8acead04cd

2023-03-02 06:40 UTC, lukehb approved these changes
lgtm!

2023-03-02 06:41 UTC, merged