Updating the Frontend Docs
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #152
Opened 2023-03-15 05:16 UTC by StomyPX

Not ready for merging yet (not by a long shot). Preliminary pull request made so there's somewhere for review feedback to live.

2023-03-15 05:49 UTC, lukehb requested changes

2023-03-15 05:49 UTC, lukehb commented on Frontend/Docs/Communicating from UE5 to the Player Page.md
> +1.  In your Unreal Engine application, any time you want to emit an event to the player page, you need an actor with a **Pixel Streaming Input** component. This component has access to the **Send Pix
> to indicate to the player page what event has happened

to 

> to send a message to the web frontend.

2023-03-16 04:49 UTC, StomyPX commented on Frontend/Docs/Communicating from UE5 to the Player Page.md
> +1.  In your Unreal Engine application, any time you want to emit an event to the player page, you need an actor with a **Pixel Streaming Input** component. This component has access to the **Send Pix
Done

2023-03-16 06:44 UTC, lukehb requested changes
Left some feedback on the customizing input options page

2023-03-16 06:44 UTC, lukehb commented on Frontend/Docs/Customizing Player Input Options.md
>  The following options are available in the frontend library:
> The following options are available in the frontend library:

to

> The following options are available in the frontend library to customize input:

2023-03-16 06:44 UTC, lukehb commented on Frontend/Docs/Customizing Player Input Options.md
> +|   HoveringMouseMode  |  false  | Determines whether or not the player widget captures and locks the mouse when the player interacts with the widget. When enabled, the mouse cursor hovers over the p
> player widget

to

> video element

2023-03-16 06:44 UTC, lukehb commented on Frontend/Docs/Customizing Player Input Options.md
> +| FakeMouseWithTouches |  false  | When this option is enabled, and the user is viewing the stream on a device with a touch screen such as a smartphone or tablet, this setting causes single-finger to
Remove comma from:

> When this option is enabled,

2023-03-16 06:44 UTC, lukehb commented on Frontend/Docs/Customizing Player Input Options.md
> +When creating a frontend implementation, these options are visible via the `Config` object required in order to create a `PixelStreaming` stream for your frontend application. Simply set the values y
`Config` and `PixelStreaming` could link to the relevant source files in repo?

2023-03-16 07:50 UTC, DenisTensorWorks commented on Frontend/Docs/Communicating from the Player Page to UE5.md
> +You need to bind this event once, typically at the start of your game. Each time any player HTML page connected to an instance of your Unreal Engine application calls the `emitUIInteraction`function,
> application calls the `emitUIInteraction`function

to

> application calls the `emitUIInteraction` function 

(note the space)

2023-03-17 00:11 UTC, StomyPX commented on Frontend/Docs/Customizing Player Input Options.md
>  The following options are available in the frontend library:
Done

2023-03-17 00:12 UTC, StomyPX commented on Frontend/Docs/Customizing Player Input Options.md
> +|   HoveringMouseMode  |  false  | Determines whether or not the player widget captures and locks the mouse when the player interacts with the widget. When enabled, the mouse cursor hovers over the p
Done

2023-03-17 00:12 UTC, StomyPX commented on Frontend/Docs/Customizing Player Input Options.md
> +| FakeMouseWithTouches |  false  | When this option is enabled, and the user is viewing the stream on a device with a touch screen such as a smartphone or tablet, this setting causes single-finger to
Done

2023-03-17 00:13 UTC, StomyPX commented on Frontend/Docs/Customizing Player Input Options.md
> +When creating a frontend implementation, these options are visible via the `Config` object required in order to create a `PixelStreaming` stream for your frontend application. Simply set the values y
I've linked them for now to the absolute URLs on github. Is there a way to make them relative to the repo somehow?

2023-03-17 00:14 UTC, StomyPX commented on Frontend/Docs/Communicating from the Player Page to UE5.md
> +You need to bind this event once, typically at the start of your game. Each time any player HTML page connected to an instance of your Unreal Engine application calls the `emitUIInteraction`function,
Good catch, done

2023-03-17 03:20 UTC, lukehb commented on Frontend/Docs/Customizing Player Input Options.md
> +When creating a frontend implementation, these options are visible via the `Config` object required in order to create a `PixelStreaming` stream for your frontend application. Simply set the values y
Yeah, you should be able to.

For example see on the Docs page we do

`- [Customizing the Player Webpage](Docs/Customizing%20the%20Player%20Webpage.md)`

2023-03-20 08:06 UTC, StomyPX commented on Frontend/Docs/Customizing Player Input Options.md
> +When creating a frontend implementation, these options are visible via the `Config` object required in order to create a `PixelStreaming` stream for your frontend application. Simply set the values y
Okay, yeah I updated to these now.

2023-03-23 02:39 UTC, lukehb commented on Frontend/Docs/Customizing the Player Webpage.md
> +The Pixel Streaming Signaling and Web Server provides a sample player page that is already set up to stream in media from your Unreal Engine application and to send mouse, keyboard, and touch events
> Signaling

to

> Signalling

not sure why, but convention throughout source and docs is two l's

2023-03-23 02:42 UTC, lukehb commented on Frontend/Docs/HTML Page Requirements.md
> +*   You can customize the `HomepageFile` parameter for the Signaling and Web Server, and set the path to the filename of your custom HTML player page relative to the [Frontend implementations source
> Signaling

to

> Signalling

2023-03-23 02:43 UTC, lukehb requested changes
Very good docs writing. Made some minor suggestions.

2023-03-23 02:55 UTC, lukehb approved these changes
Made the small changes myself. Approved.

2023-03-23 02:56 UTC, merged