Unit tests for library
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #156
Opened 2023-03-15 13:37 UTC by hmuurine

# Summary

Added some Unit tests for the library project:
- Added Jest dependencies and configuration for running unit tests with `npm run test`
- Added initial unit tests for the public API:
   - Config: test setting & getting configuration, initial settings, persisting data to URL
   - AFKController: test that AFK timers and events work as expected
   - PixelStreaming: test mocked WebSocket connection, mocked WebRTC connection, mocked video playback, events emitted in various stages of the connection process, statistics emitter, data channel send/receive
- Mocks for WebSocket, MediaStream and WebRTC classes that are not natively supported in Jest/Node/jsdom test environment

# Test Plan
- Ran the unit tests and verified that they worked
- Broke some of the functionality deliberately and verified that this was caught in unit tests

2023-03-15 13:39 UTC, hmuurine commented on Frontend/library/src/Inputs/GamepadController.ts
> +                }
Fixed an issue found in unit tests: `navigator.getGamepads` is not available in all environments. This is checked in some other places using this function, but here the check was missing, and caused issues.

2023-03-15 13:41 UTC, hmuurine commented on Frontend/library/src/PeerConnectionController/PeerConnectionController.ts
> +                ?.createOffer(offerOptions)
Fixed an issue found in unit tests: `this.peerConnection` is set to `null` if `close()` is called, so needs a check everywhere it is accessed. Some of these functions are async functions that might still be executing after `close()` in some edge cases if `close()` is called just when some async event is triggered.

2023-03-15 13:44 UTC, hmuurine commented on Frontend/library/src/__test__/mockMediaStream.ts
> +    }
Implemented only the functions that are actually called directly by the code, and the rest of them are throwing an error if called. If adding new unit tests later, might need to implement some additional mock functions, if they hit one of the unimplemented mock methods.

2023-03-15 14:39 UTC, vshjxyz commented
Huge one! That's awesome, we should leverage (if possible) having a public repo to integrate coverage reports into PRs to keep track and avoid merging PRs without enough coverage. Since this is a library aimed to be consumed by multiple clients that can also help on external contributions, but I'm probably thinking too far ahead (?)

2023-03-16 05:24 UTC, lukehb commented
Amazing PR! Great work.

A few additional requests on top of the comments I have already left:

1. Can it also include a github action for running these tests against PRs that touch the Frontend/library files?
2. Can you update frontend readme.md informing users how to run these tests by hand.

2023-03-16 05:25 UTC, lukehb requested changes
Left some minor comments.

2023-03-16 05:25 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        const sdp = "v=0\r\no=- 974006863270230083 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS pixelstreaming_audio_stream_id pixelstrea
This SDP seems to be repeated across many tests. Any reason we can't make this a constant in one place instead?

2023-03-16 05:25 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        });
Quite a few of these tests that actually go all the way to setting up the Pixel Streaming object seem to have a lot of shared functionality, could we make a function for this sort of setup logic and have it used across multiple tests?

2023-03-16 06:37 UTC, hmuurine commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        });
You are right, it would make sense to extract the common steps to util functions to make it more readable and maintainable.

2023-03-16 06:38 UTC, hmuurine commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        const sdp = "v=0\r\no=- 974006863270230083 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS pixelstreaming_audio_stream_id pixelstrea
Good idea, I'll extract the common constants and common setup steps.

2023-03-16 12:22 UTC, hmuurine commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        });
Extracted in commit https://github.com/EpicGames/PixelStreamingInfrastructure/pull/156/commits/064275d7cc303df189e3cfc70ea53243d5065e6e

2023-03-16 12:22 UTC, hmuurine commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        const sdp = "v=0\r\no=- 974006863270230083 2 IN IP4 127.0.0.1\r\ns=-\r\nt=0 0\r\na=group:BUNDLE 0 1 2\r\na=extmap-allow-mixed\r\na=msid-semantic: WMS pixelstreaming_audio_stream_id pixelstrea
Done in https://github.com/EpicGames/PixelStreamingInfrastructure/pull/156/commits/064275d7cc303df189e3cfc70ea53243d5065e6e

2023-03-16 13:44 UTC, hmuurine commented
>     1. Can it also include a github action for running these tests against PRs that touch the Frontend/library files?

Added an action that runs the unit tests if `Frontend/library/**` files change. The action is run for `master` commits and all PRs that have target branch `master`. You can see the actions triggered already in this PR. Also tested that test failures are properly detected:
![Screenshot 2023-03-16 at 15 43 27](https://user-images.githubusercontent.com/8232602/225635920-11bca5ff-40f1-4a41-abca-5b1c2141605a.png)


>     2. Can you update frontend readme.md informing users how to run these tests by hand.
Done in https://github.com/EpicGames/PixelStreamingInfrastructure/pull/156/commits/a1c9f466a840eb5f7c9690a6108ba90f54c9fe7c

2023-03-17 02:39 UTC, lukehb approved these changes
lgtm!

2023-03-17 02:41 UTC, merged