Change implementations/EpicGames to implementations/typescript #166
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #177
Opened 2023-03-26 15:49 UTC by gunsha

## Relevant components:
- [ ] Signalling server
- [ ] Frontend library
- [ X ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
What problem does this PR address?
rename implementations/EpicGames to implementations/typescript as mentioned on #166
## Solution
How does this PR solve the problem?

## Documentation
If you added a new feature or changed an existing feature please add some documentation here.

Or better yet, link to the relevant `/Docs` update in your PR.

## Test Plan and Compatibility
What steps have you taken to ensure this PR maintains compataibility with the existing functionality? 

Or better yet, link to the unit tests that accompany this PR.

2023-03-27 04:58 UTC, lukehb requested changes
Seems to be missing Windows setup frontend -
 https://github.com/EpicGames/PixelStreamingInfrastructure/blob/dce89db3f66fc8b545e4d2e6ef2912c17596f2ff/SignallingWebServer/platform_scripts/cmd/setup_frontend.bat#L68

2023-03-27 06:52 UTC, Belchy06 commented
Are the workflow files per repo or are they modifiable per branch as well?

If they can be modified per branch, they will also need to be updated.

2023-04-02 23:39 UTC, lukehb commented
This is an automated reply: I will be out of office for the next two weeks. Please bump this ticket in two weeks.

2023-04-03 23:14 UTC, Belchy06 requested changes

2023-04-03 23:14 UTC, Belchy06 commented on SignallingWebServer/platform_scripts/cmd/setup_frontend.bat
> +  pushd %CD%\Frontend\implementations/typescript
This needs to be `\typescript`

2023-04-03 23:34 UTC, gunsha commented on SignallingWebServer/platform_scripts/cmd/setup_frontend.bat
> +  pushd %CD%\Frontend\implementations/typescript
@Belchy06 fixed

2023-04-04 01:36 UTC, Belchy06 approved these changes

2023-04-13 01:46 UTC, Belchy06 commented
Thanks for fixing those requested changes @gunsha.

We're winding down active development in preparation for the 5.2 launch, only merging critical issues.

We'll merge this in once 5.2 has launched.

2023-07-18 02:44 UTC, Belchy06 commented
Rebased this PR on master. Once @lukehb approves it should be good to merge!

2023-07-18 06:18 UTC, lukehb approved these changes

2023-07-18 06:32 UTC, merged