Remove hardcoded protocol
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #19
Opened 2022-07-18 03:45 UTC by Belchy06

Currently, if a user were to add a new message type to pixel streaming, they need to update both the front end and the c++ to support this new message type.

This PR adds the ability for users to simply register their new message in the c++ and all peers connected will simply receive the updated protocol and keep working as intended.

We keep a populated default protocol to maintain backwards compatibility with previous engine versions.

2022-07-25 01:53 UTC, mentalnote requested changes, later dismissed

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
> -            if (currButton.pressed && !prevButton.pressed) {
what's the purpose of this change?

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
>                  if (i == 6) {
Should really replace all these magic numbers with variables that represent what they are

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
> +    // Old EToPlayerMsg enum
What's the difference between these key-value entries and the ones where you additionally set `byteLength: 0` and `structure: []`?

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage("MouseWheel", [ e.detail * -120, coord.x, coord.y ]);
Should give this -120 a variable and name that represents its purpose

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage(type, [ 1, coord.x, coord.y, fingerIds[touch.identifier], 255 * touch.force, coord.inRange ? 1 : 0 ]);
Give the `1` at the start of the created array here a variable and name describing its purpose along with the `255` (MaxByteValue)

2022-07-25 01:53 UTC, mentalnote commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage(type, [ 1, coord.x, coord.y, fingerIds[touch.identifier], 255 * touch.force, coord.inRange ? 1 : 0 ]);
Actually, shouldn't that `1` be `touches.length`?

2022-07-25 02:00 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> -            if (currButton.pressed && !prevButton.pressed) {
Just code cleanliness. We had a lot of if/else to check if the this event should be emitted as a repeat press or not.

I found the only difference between this first if block and the last elseif was the value of the last parameter to emitControllerButtonPressed (L118 / L136)

2022-07-25 02:24 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage(type, [ 1, coord.x, coord.y, fingerIds[touch.identifier], 255 * touch.force, coord.inRange ? 1 : 0 ]);
With the rewrite of the UE side protocol, we are unable to support message like this where there may be a varying amount of information unless it's parsed as a string (eg the descriptors). To maintain backwards compatibility we now send each touch individually and such the touches array now only has a length of 1

2022-07-25 02:48 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage("MouseWheel", [ e.detail * -120, coord.x, coord.y ]);
This has been fixed by instead using the standardized `onwheel` event instead of `onmousewheel` for chrome and `DOMMouseScroll` for firefox.

2022-07-25 02:53 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> +    // Old EToPlayerMsg enum
the ones below are for receiving messages from UE in which case they are always formatted as a Uint8Array. All the below messages are handled in `webRtcPlayerObj.onDataChannelMessage`

2022-07-26 05:21 UTC, lukehb requested changes, later dismissed
Left some comments mostly about changing how the API surface looks.

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +        "structure": [ "uint16" ]
Seems a little odd that KeyDown/Up has different size to KeyPress

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage(type, [ numTouches, coord.x, coord.y, fingerIds[touch.identifier], MaxByteValue * touch.force, coord.inRange ? 1 : 0 ]);
Have you verified sending touches in this way preserves multi-touch capabilities, like pinch/zoom?

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
>      webRtcPlayerObj.onDataChannelMessage = function(data) {
I was hoping here we could end up with some API surface in the frontend like so:

`RegisterInputProtocolHandler("FreezeFrame", OnFreezeFrameMessage);`

Then when we get the protocol message we handle it by having already registered the following:

`RegisterInputProtocolHandler("Protocol", OnProtocolMessage);`

where OnProtocolMessage looks very roughly like so:

```
function onProtocolMessage(protocolJSON){
    this.protocolJSON = protocolJSON
    this.protocolHandlers = {}
    for(let protocol of protocolJSON){
        if(protocol in this.registeredProtocolHandlers){
            this.protocolHandlers[protocol] = this.registeredProtocolHandlers[protocol];
        }
        else {
            console.error(`There was no registered protocol handler for ${protocol} - try adding one using RegisterInputProtocolHandler(${protocol}, myHandler)`);
        }
    }
}
```

And ofc for backwards compatibility we will pre-populate the protocol handlers with all the defaults we have supported in the past versions.

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +    // Old EToPlayerMsg enum
Should the protocol differentiate between streamer and player message types? ToStreamer/FromStreamer - it seems like it could be helpful? If they are split out like so I think it becomes more kosher to have these ones below that have no structure/byte length. Is it worth saying structure is uint8 array for consistency?

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +function sendInputMessage(messageType, indata = []) {
I would consider calling this sendInputProtocolMessage()

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +			    byteOffset += 1;
weird whitespace or just me?

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +    "IFrameRequest": {
Does IFrameRequest work atm? If not, can we make it work?

If it does work, let's hook up a button for this in the settings panel, this seems to come up often enough where people want to request a keyframe from browser side.

2022-07-26 05:21 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +            emitDescriptor("ToStreamerCommand", { "Encoder.MinQP": minQP });
Instead of hardcoded strings, these should probably come from a DefaultProtocolKeys.ToStreamerCommand or something like that.

2022-07-27 09:52 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +    registerMessageHandler(MessageDirection.ToStreamer, "GamepadAnalog", sendMessageToStreamer);
Beautiful

2022-07-27 09:52 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +     * TODO
Why todo?

2022-07-27 09:53 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +                        console.error(`ToStreamer->${messageType} protcol definition was malformed`);
Error message should mention it was malformed because it didn't contain both id and byteLength and should print what the message was.

2022-07-27 09:54 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +                        console.error(`ToStreamer->${messageType} protcol definition was malformed`);
Same with structure parsing below

2022-07-27 09:55 UTC, lukehb commented on SignallingWebServer/scripts/app.js
> +                        console.error(`FromStreamer->${messageType} protcol definition was malformed`);
Same as above comment, also typo in protocol

2022-07-27 10:02 UTC, lukehb commented on SignallingWebServer/scripts/twoWapMap.js
> +}
Let's keep this in app.js until we introduce a bundler

2022-08-02 02:16 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> +            sendInputMessage(type, [ numTouches, coord.x, coord.y, fingerIds[touch.identifier], MaxByteValue * touch.force, coord.inRange ? 1 : 0 ]);
Verified that multi-touch still works with UEs inbuilt on-screen joysticks

2022-08-02 02:16 UTC, Belchy06 commented on SignallingWebServer/scripts/app.js
> +    "IFrameRequest": {
It does now!

2022-08-04 07:18 UTC, lukehb approved these changes
lgtm

2022-08-04 07:18 UTC, merged