Signaling message reference doc
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #271
Opened 2023-06-16 02:21 UTC by mcottontensor

## Relevant components:
- [ x ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
Signaling messages are currently black magic and undocumented

## Solution
Adding a reference for every signaling message.

## Documentation
Yes

2023-06-16 03:17 UTC, lukehb requested changes
Left some comments.

Additional to those comments I think it would good to have a sequence diagram of signalling between for instance:

Player <-> SS <-> Streamer

Github supports such diagrams in markdown: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +## Player Sent Messages
- Add a top level heading called `Signalling Protocol` 
- Followed by a short explanation of the page
- Followed by a ToC the sections of this page (as it is quite a long one)

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the Signaling Server. Requests the list of streamer ids currently connected to the Signaling Server. The server will reply with a [streamerList](#streamerList)
Signaling to `Signalling` (two l's) - for consistency with the rest of the repo.

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +| streamerId | The id of the stream to subscribe to. |
I would consider a new column in all these tables for the `type` of parameter, e.g. `string` `int` etc

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the signaling server. Tells the signaling server that the player wishes to unsubscribe from the current stream. The player must have previously used the `subscribe` message for
Where there is some dep between messages can do a section link to hyperlink to the referred section.

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is forwarded to the currently subscribed to Streamer. Supplies an SDP offer to the Streamer to answer. The player must have previously used the `subscribe` message to successfully subscribe t
I would consider putting a glossary of terms at the start of this page:

- streamer
- player
- SFU
- signalling server
- SDP
- ICE candidate

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the Signaling Server. Specifies an id for the streamer.
Useful for identifying streamers in cases where they are multiple streamers (like multi-streams or running at scale in the cloud)

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is forwarded to a connected SFU. Sends a preferred layer index to a connected SFU for a specified player.
Useful for switching between SFU quality layers to force a certain resolution/quality option either as part of UX or testing

2023-06-16 03:17 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is a reply to [ping](#ping) from a Streamer. Replies with the time from the ping message.
Seems `playerConnected` message is missing?

2023-06-16 03:17 UTC, lukehb reviewed
Left some comments.

Additional to those comments I think it would good to have a sequence diagram of signalling between for instance:

Player <-> SS <-> Streamer

Github supports such diagrams in markdown: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

2023-06-16 03:24 UTC, lukehb commented
@mcottontensor I would also recommend the introduction of a readme.md in the root of the SignallingWebServer directory and it can have something like the following:

# Getting Started

## Running
Run `node cirrus.js` or `platform_scripts/cmd/run_local.bat|.sh`

## Changing the frontend
Replace the contents of `/Public`

# Documentation
[Signalling Protocol](./SignallingProtocol.md)

2023-06-16 05:24 UTC, mcottontensor commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the signaling server. Tells the signaling server that the player wishes to unsubscribe from the current stream. The player must have previously used the `subscribe` message for
Yeah I have been trying to do that, but in Obsidian which I'm using to write the md, I have issues with repeated headings and linking to a unique one, ie. there are multiple 'offer' headings, and I also can't seem to add invisible anchors that I can link to with unique names. Maybe the gh md interpreter can handle things differently.

2023-06-19 00:43 UTC, mcottontensor commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the Signaling Server. Specifies an id for the streamer.
Is this just suggested extra text for the description?

2023-06-19 01:36 UTC, lukehb commented on SignallingWebServer/Docs/Messages.md
> +Message is consumed by the Signaling Server. Specifies an id for the streamer.
Yep

2023-06-19 03:05 UTC, mcottontensor commented
> Left some comments.
> 
> Additional to those comments I think it would good to have a sequence diagram of signalling between for instance:
> 
> Player <-> SS <-> Streamer
> 
> Github supports such diagrams in markdown: https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

Was looking into this but a lot of messages would just be a->b or a->b->c and would then trigger different messages sent back with their own sequence.
I'm wondering if it might be worth to separate it out into its own section rather than per message... Say a section for negotiation or or stats capture, or something along those lines.

2023-06-19 10:23 UTC, lukehb commented
I agree, on consideration a sequence diagram for negotiation would be ideal!

2023-06-20 08:08 UTC, lukehb commented
Recent commit had code changes as opposed to pure docs, can we separate that into its own PR?

2023-06-20 21:33 UTC, lukehb reviewed
I have also think now is the time we add a section to this document called

# Version
1.0.0 - Current

Major version number - breaking protocol change such as a required new message or field or deleting an existing message.
Minor version number - independent new message.
Hotfix version - a non-breaking new field in an existing message type.

2023-06-21 00:00 UTC, mcottontensor commented
> Recent commit had code changes as opposed to pure docs, can we separate that into its own PR?

There's no code changes? Perhaps you saw the merge from master?

2023-06-29 05:35 UTC, merged