add create, reconnect, update events and tests
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #273
Opened 2023-06-16 05:43 UTC by jibranabsarulislam

## Relevant components:
- [ ] Signalling server
- [ x ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
#270 

## Solution
uses contextual structure of methods and events to add the new events

## Documentation
WIP

## Test Plan and Compatibility
event emitters should not affect functionality; implementation of these functions are complemented by the new tests

2023-06-16 05:44 UTC, jibranabsarulislam commented
please feel free to provide your feedback and suggestions, especially with the tests; they're a top weakness of mine

2023-06-16 06:26 UTC, lukehb commented on Frontend/library/src/Util/EventEmitter.ts
> +    | StreamConnectEvent
Considering when this event fire does, I would prefer the name `StreamPreConnect`

2023-06-16 06:26 UTC, lukehb commented on Frontend/library/src/Util/EventEmitter.ts
> +    | StreamDisconnectEvent
Similiar here, `StreamPreDisconnect`

2023-06-16 06:27 UTC, lukehb requested changes, later dismissed
Looks good, thanks for this.

Can I ask you change the events to StreamPreConnect and StreamPreDisconnect - sorry that wasn't captured in the issue originally.

2023-06-16 07:24 UTC, jibranabsarulislam commented
> Looks good, thanks for this.
> 
> Can I ask you change the events to StreamPreConnect and StreamPreDisconnect - sorry that wasn't captured in the issue originally.

no worries, got those changes a small refactor pushed. Thank you!

If possible, can I be tagged on early discussion of these events' implementation? i'm interested in learning more about the connection/networking within pixelstreaming

2023-06-16 07:28 UTC, jibranabsarulislam commented
no worries—pushed!
thank you @lukehb

2023-06-20 03:46 UTC, mcottontensor approved these changes

2023-06-21 00:26 UTC, mcottontensor approved these changes

2023-06-21 00:26 UTC, mcottontensor commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        expect(streamReconnectSpy).toHaveBeenCalled();
This appears to be failing tests. I believe because reconnect isn't being called since connect is manually immediately called.

2023-06-21 00:28 UTC, merged

2023-06-21 00:46 UTC, jibranabsarulislam commented on Frontend/library/src/PixelStreaming/PixelStreaming.test.ts
> +        expect(streamReconnectSpy).toHaveBeenCalled();
ah, my mistake, thank you for fix!