Auto connect on new streamer
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #358
Opened 2023-09-08 03:03 UTC by mcottontensor

## Relevant components:
- [x] Signalling server
- [x] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
If the front end tries to join a stream before the streamer is connected it requires a click to connect once the streamer has connected.

## Solution
This adds a new signalling message to the signalling server that broadcasts to all players that a new streamer has connected to the signalling server. The front end will respond to this if it's waiting, by auto joining the new stream.

## Test Plan and Compatibility
None

2023-09-08 03:43 UTC, lukehb approved these changes, later dismissed

2023-09-08 03:43 UTC, lukehb commented on Frontend/library/src/WebSockets/SignallingProtocol.ts
> +    MessageStreamerConnected,
Hmmm, I would really prefer us to not add a new protocol message until we have a mechanism to transmit the signaling protocol and version.

If we absolutely can't achieve this another way then I guess by our own rules:

https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/SignallingWebServer/Docs/SignallingProtocol.md

This qualifies as a minor version bump in the signalling protocol (as it is independent and not a required message).

Could we also just sit in a timer and try again every few seconds if we couldn't connect and got back no streamers connected. I know it is more wasteful - but also no signaling change.

What do you think @mcottontensor?

2023-09-08 03:44 UTC, mcottontensor commented on Frontend/library/src/WebSockets/SignallingProtocol.ts
> +    MessageStreamerConnected,
Fair. I can update it to just be a timer.

2023-09-11 02:46 UTC, lukehb requested changes
Tiny change to expose interval as a setting.

2023-09-11 02:46 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +        this.autoJoinTimer = setTimeout(() => this.tryAutoJoin(), 3000);
We should expose this time interval as a setting too.

2023-09-11 02:48 UTC, mcottontensor commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +        this.autoJoinTimer = setTimeout(() => this.tryAutoJoin(), 3000);
No problem.

2023-09-11 03:04 UTC, lukehb commented on Frontend/library/src/Config/Config.ts
> +                NumericParameters.WaitRetryDelay,
Can this be called like `StreamerAutoJoinInterval` instead?

2023-09-11 03:04 UTC, lukehb approved these changes
Approved with suggestion to change most recent setting name.

2023-09-11 03:10 UTC, lukehb approved these changes

2023-09-11 03:11 UTC, merged