Fixes for Streamers changing IDs when connecting & Updates to SFU behaviour relating to multi streamer changes.
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #411
Opened 2023-10-25 01:13 UTC by mcottontensor

## Relevant components:
- [x] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [x] Platform scripts
- [x] SFU

## Problem statement:
Streamer IDs changing:
Streamers need to identify themselves so when they first connect they are assigned a temporary ID. If a player attempts to connect while this temporary name is assigned it can lead to stuck behaviour.

SFUs with multi streamer behaviour:
When the multi streamer change went in the SFU behaviour was kind of hacked into the flow. Only one SFU could be connected at all and it was assumed that there was always only one streamer.

## Solution
Streamer IDs changing:
Now when streamers connect, they are not "published" in the streamer list until they ID themselves. If they do not ID themselves within a time, they are assigned an ID. This prevents peers connecting to streamers during their ID negotiation.

SFUs with multi streamer behaviour:
There are several new configuration options with the SFU. The SFU ID, which is used to identify the SFU as a streamer on the signalling server. This ID will show up in the streamers list when the SFU is streaming. And the subscribe streamer ID which tells the SFU what streamer ID we are looking to forward. If it cannot find the specified streamer it will request the streamer list on a timeout that is specified in the config until it finds the streamer it's looking for.
Additionally the SFU can now start/stop streaming which will control when the SFU shows up in the streamer list on the signalling server. The SFU will start streaming when it connects to the streamer it's configured to forward, and stop streaming when it loses this connection.

## Documentation
Documentation has been added to the SFU configuration file. Documentation for the streamer ID fix is not needed.

## Test Plan and Compatibility
I have manually run through various scenarios of connecting and disconnecting different components in different orders and switching between SFU and DefaultStreamers. We will need to do a usual QA pass over this change.

2023-10-27 04:17 UTC, mcottontensor commented
Fixes #350

2023-10-30 05:21 UTC, lukehb reviewed
Left some comments and questions

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +const LegacyStreamerPrefix = "__LEGACY_STREAMER__"; // old streamers that dont know how to ID will be assigned this id prefix.
Is changing this string problematic @Belchy06 ?

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +}
Legacy id creation change to be prefix + number, @Belchy06 is this also okay for backward compat?

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +	return id;
A bit curious what is happening here.

Is there correct: we do a check to see if the base id of an existing streamer matches the new id, then if they are matching, then increment the numeric part of the id, is that right?

Also is the base id an ip address now? 

So my summary here is I don't like the regex, it seems a bit fragile.

Can we store the id as a struct so we have the addr and increment stored as fields on the struct instead of encoding them both in a single string?

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +	return ""; // no available id
Instead of for-loop here can we just store a global legacyId increment. This for loop gets slower each unique streamer we add. I get the size of the loop is small, but still, I think legacyId increment lets us have unlimited legacy streamer ids and is O(1) to generate a new id.

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +}
Pretty much same comment as loop for generating legacy streamer id, can we just have a global for SFU id generator.

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +	let streamer = new Streamer(temporaryId, ws, StreamerType.Regular);
So to be clear, streamer ids will be now set to their remote address (+ potentially some id appended to the back). Is there a separator between the remote address and the appended id?

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +sfuMessageHandlers.set('listStreamers', onPlayerMessageListStreamers);
Shouldn't `onPlayerMessageListStreamers` have some check to see if streamer id `commited` (just for safety as the code changes in the future)?

2023-10-30 05:21 UTC, lukehb commented on SignallingWebServer/platform_scripts/cmd/setup_frontend.bat
> +  set PATH=%PATH%;%NodeDir%
Will want Michael to test this works on AWS

2023-10-30 05:23 UTC, lukehb commented
Given there is some changes to fairly load bearing code I am going to ask @Belchy06 to review also.

And once reviews have been done I'm gonna ask @MWillWallT to give this a QA pass:

- Using all the different infra components and configs on AWS - Linux and Windows
- Testing whether previous version of UE 5.0 - 5.3 still connect to this signalling server, SFU, and matchmaker.

2023-10-30 05:29 UTC, Belchy06 commented on SignallingWebServer/cirrus.js
> +const LegacyStreamerPrefix = "__LEGACY_STREAMER__"; // old streamers that dont know how to ID will be assigned this id prefix.
Should be fine. 

We just assign them an ID so regardless of what they're assigned, the current code paths will be fine.

2023-10-30 05:30 UTC, Belchy06 commented on SignallingWebServer/cirrus.js
> +}
Same as above, should be fine.

2023-10-30 05:32 UTC, mcottontensor commented on SignallingWebServer/cirrus.js
> +	return id;
This is to just prevent 2 streamers from being the same ID. So if DefaultStreamer already exists and someone tries to register as DefaultStreamer, they will be assigned DefaultStreamer1 and the next DefaultStreamer2.
The id is only set to the address of the connecting streamer while we're waiting for it to register itself. It should never actually be used in anything other than logging.

2023-10-30 05:37 UTC, mcottontensor commented on SignallingWebServer/cirrus.js
> +	let streamer = new Streamer(temporaryId, ws, StreamerType.Regular);
No. This is just temporary and allows us to get a better idea of what's happening if anything is logged while this streamer is negotiating its id. It should never actually be used for anything but logging.

2023-10-30 05:40 UTC, mcottontensor commented on SignallingWebServer/cirrus.js
> +sfuMessageHandlers.set('listStreamers', onPlayerMessageListStreamers);
It could just for sanity but the `streamers` list should not contain anything non committed. `committed` is referring to the act of adding the streamer to that list.

2023-10-30 05:47 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +	return id;
Okay understood. I still think the code/intent is clearer if we store id like

{
prefix: String,
increment: Number,
toString: ()->String
}

Not sure how much other stuff that messes up though. I guess it turns it into a pretty big refactor then?

Does the regex break if I set my streamer id to an integer say: `137`

2023-10-30 05:49 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +const LegacyStreamerPrefix = "__LEGACY_STREAMER__"; // old streamers that dont know how to ID will be assigned this id prefix.
There is no UE side code that assumes `_LEGACY_` ?

2023-10-30 05:51 UTC, lukehb commented on SignallingWebServer/cirrus.js
> +const LegacyStreamerPrefix = "__LEGACY_STREAMER__"; // old streamers that dont know how to ID will be assigned this id prefix.
I can see `Engine\Plugins\Media\PixelStreaming\Source\PixelStreamingServers\Private\SignallingServer.cpp` does use that string. But I don't think that matters here, as that is simply the UE side signalling server.

2023-10-30 06:07 UTC, lukehb commented on Frontend/library/src/Config/Config.ts
> -        );
Is the idea here that now that we support multiple streamers, they just select the SFU just like any other streamer? If so, agreed.

2023-10-30 06:10 UTC, lukehb requested changes
Few more questions and spotted a doc change that needs to go in too.

2023-10-30 06:10 UTC, lukehb commented on Frontend/ui-library/src/Config/ConfigUI.ts
> -        );
Removing this setting means you should also update this page: 

https://github.com/EpicGames/PixelStreamingInfrastructure/blob/master/Frontend/Docs/Settings%20Panel.md

2023-10-30 22:12 UTC, mcottontensor commented on SignallingWebServer/cirrus.js
> +	return id;
I think that's needlessly complex because we just want to come up with a unique name in the case of name clashes. Once the name is generated there's no benefit to breaking it down since it's all just reported to the user via the streamer list.
Addressed the issue where the streamer id is totally numeric now.

2023-10-30 22:15 UTC, mcottontensor commented on Frontend/library/src/Config/Config.ts
> -        );
Yes. There is also room to improve it slightly to report the "type" of the streamer in the streamer list in the case where someone wants to "prefer" an sfu over other available streamers, programmatically.

2023-10-30 22:20 UTC, mcottontensor commented on Frontend/ui-library/src/Config/ConfigUI.ts
> -        );
Updated.

2023-10-31 06:03 UTC, lukehb approved these changes

2023-10-31 06:04 UTC, lukehb commented
@mcottontensor Michael has given it the green light for QA, I have approved. You may want to consider which branches benefit from the backport using the autobackport tags.

2023-10-31 22:56 UTC, merged