Rewriting a bunch of reconnect and disconnect handling. Fixes #401
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #419
Opened 2023-11-01 02:22 UTC by mcottontensor

## Relevant components:
- [ ] Signalling server
- [x] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
In addressing #401 I noticed there was a lot of clumsiness when dealing with disconnections and reconnections. There were several situations that would lead to reconnection loops, or incorrect status reporting etc.

## Solution
I have cleaned up and streamlined a bunch of the logic around when to connect and which streamers to auto subscribe to. I have also made changes to how the reporting is done on the overlay.

## Documentation

## Test Plan and Compatibility
A lot of manual tests and the usual npm tests. Will need further QA.

2023-11-01 02:27 UTC, mcottontensor commented
Fixes #401

2023-11-01 05:02 UTC, lukehb commented on Frontend/library/src/Util/EventEmitter.ts
> +        autoSelectedStreamerId: string;
If null type is no longer supported I support comment above should change?

2023-11-01 05:03 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> -    disconnectMessageOverride: string;
lol, what a pointless comment it had before

2023-11-01 05:06 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +            this.setVideoEncoderAvgQP(0);
Maybe add comment here, this may be unintuitive that (I assume) the reason this is done is reset the stream quality icon.

2023-11-01 05:07 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> -    restartStreamAutomatically() {
Thank you. Thank you. Thank you. Much better name.

2023-11-01 05:08 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
>              this.pixelStreaming._onWebRtcAutoConnect();
This one is the other one with a bad name imo.

2023-11-01 05:09 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.ts
> -        this._webRtcController.restartStreamAutomatically();
Nice.

2023-11-01 05:10 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.ts
> +        this._webRtcController.tryReconnect("");
Maybe just "Reconnecting..." ?

2023-11-01 05:10 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +    disconnectMessageOverride: string;
Do we actually need this property at all?

2023-11-01 05:19 UTC, lukehb commented on Frontend/ui-library/src/Application/Application.ts
> +                message = `Multiple streamers available. Select from the settings menu.`;
Perhaps
 
 > Multiple streamers available. Select one from the settings menu.
 
 > Multiple streamers available. Select a streamer from the settings menu.

2023-11-01 05:20 UTC, lukehb requested changes
Left a few minor comments.

2023-11-01 05:27 UTC, lukehb commented
@MWillWallT This PR changes some loading bearing code around reconnections and disconnections.

Can I get you to test the following:

- Reconnection/disconnect working as expected with one streamer
- Reconnection/disconnect working as expected with one streamer and multiple peers
- AFK working as expected with one streamer and multiple peers
- Killing the streamer midstream then putting it back up auto reconnects fine
- Killing the streamer midstream then waiting for reconnects to exhaust, putting the streamer back up then clicking connect works fine
- Change the reconnect time interval and attempts works as expected
- Connecting/disconnecting/reconnecting works fine when there are multiple streamers
- Matchmaker with multiple UEs works fine
- Anything else you think that would make sense for reconnection flows.
- Tested on Chrome, Firefox, Safari, Android, and iOS.

Also keep in mind some of the messages displayed on the frontend change in this PR. Might be worth seeing if all the common ones are worded correctly and make sense for the scenario they show up in.

2023-11-01 05:28 UTC, mcottontensor commented on Frontend/library/src/Util/EventEmitter.ts
> +        autoSelectedStreamerId: string;
string type allows null by default.

2023-11-01 05:29 UTC, mcottontensor commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +            this.setVideoEncoderAvgQP(0);
Honestly I'm as clueless as you. I just copied this from existing behaviour.

2023-11-01 05:29 UTC, mcottontensor commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
>              this.pixelStreaming._onWebRtcAutoConnect();
tryReconnect? or _onWebRtcAutoConnect?

2023-11-01 05:31 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +            this.setVideoEncoderAvgQP(0);
I am pretty sure it is what I said, maybe just add a comment above it saying

> This is done to reset the stream quality icon.

2023-11-01 05:32 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
>              this.pixelStreaming._onWebRtcAutoConnect();
`_onWebRtcAutoConnect()`

2023-11-01 05:32 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
>              this.pixelStreaming._onWebRtcAutoConnect();
Don't have to do anything about it in this PR, but if the opportunity comes up that one is also in my sights.

2023-11-01 05:50 UTC, mcottontensor commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +    disconnectMessageOverride: string;
Yeah we still set it internally and use it later. I've updated the name to be less verbose, however.

2023-11-02 01:07 UTC, MWillWallT commented
I've gone through and tested as many re-connection configs as I can, as well as all the suggested you mentioned @lukehb 
All good on this front

2023-11-02 01:11 UTC, lukehb approved these changes

2023-11-02 01:12 UTC, lukehb commented
QA has passed, you can consider backporting to 5.2, 5.3 too with this one I think.

2023-11-02 01:26 UTC, merged