Bitrate negotiation on stream startup
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #425
Opened 2023-11-09 01:03 UTC by mcottontensor

- Added min/max bitrate requests for offer/answer messages
- Fixing bitrate values in the frontend units and parsing.

## Relevant components:
- [ ] Signalling server
- [x] Frontend library
- [x] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
Setting the bitrate values before starting the stream did not work.

## Solution
Added min/max bitrate values to the answer signalling message so the streamer can extract them and set them when needed.

## Documentation

## Test Plan and Compatibility
Will probably need a QA pass.

2023-11-10 03:44 UTC, lukehb requested changes
Left some comments about organising params into an struct/config object.

2023-11-10 03:44 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +        this.webSocketController.sendWebRtcOffer(offer, minBitrate, maxBitrate);
Rather than appending more parameters here (as I am certain we will want more in the future) can we instead pass an offerOptions, offerParams, offerConfig, or something like this as the additional parameter to this function/

2023-11-10 03:44 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +        this.webSocketController.sendWebRtcAnswer(answer, minBitrate, maxBitrate);
Same comment as above about an options param.

2023-11-10 03:44 UTC, lukehb commented on Frontend/library/src/WebSockets/MessageSend.ts
> +    sendFilter(key: string, value: any) {
Good idea. Can comment have an example of how it should be used.

2023-11-10 03:55 UTC, lukehb commented on Frontend/library/src/WebRtcPlayer/WebRtcPlayerController.ts
> +        const minBitrate = 1000 * this.config.getNumericSettingValue(NumericParameters.WebRTCMinBitrate);
Consider naming as minBitrateBps, although technicaly bitrate implies bps, the word bitrate is also used for kilobits and megabits quite often so I think the extra clarity here helps.

2023-11-10 03:55 UTC, lukehb requested changes
Minor changes to naming/structuring really.

2023-11-10 04:59 UTC, lukehb requested changes
Minor comment about using ExtraParams object even more.

2023-11-10 04:59 UTC, lukehb commented on Frontend/library/src/WebSockets/WebSocketController.ts
> +        const payload = new MessageSend.MessageWebRTCOffer(offer, extraParams.minBitrateBps, extraParams.maxBitrateBps);
Can the constructor of MessageSend.MessageWebRTCOffer and MessageSend.MessageWebRTCAnswer take the ExtraParameters object for the same reason (so constructor doesn't grow overlong as we add more).

2023-11-10 05:15 UTC, lukehb requested changes
Minor correct to type used I think

2023-11-10 05:15 UTC, lukehb commented on Frontend/library/src/WebSockets/MessageSend.ts
> +    constructor(answer: RTCSessionDescriptionInit, extraParams: ExtraOfferParameters) {
Offer params passed to answer?

2023-11-10 05:18 UTC, lukehb commented on Frontend/library/src/WebSockets/MessageSend.ts
> +    constructor(answer: RTCSessionDescriptionInit, extraParams: ExtraOfferParameters) {
Also comment:

> @param answer - Generated Web RTC Offer

Seems wrong in the same way, talking about offer in answer constructor.

2023-11-10 05:24 UTC, lukehb approved these changes
lgtm!

2023-11-13 21:49 UTC, merged

2023-11-14 23:41 UTC, DenisTensorWorks commented
This PR closes this issue: https://github.com/EpicGames/PixelStreamingInfrastructure/issues/275