New docs
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #429
Opened 2023-11-17 01:52 UTC by mcottontensor

## Relevant components:
- [ ] Signalling server
- [ ] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [ ] Platform scripts
- [ ] SFU

## Problem statement:
Missing documentation for several components.

## Solution
Added some brief documentation that was missing.

## Documentation
Added SignallingWebServer docs. Linked the existing Matchmaker docs. Added SFU docs.

## Test Plan and Compatibility
No testing needed.

2023-11-17 01:55 UTC, mcottontensor commented
Closes #257
Closes #256
Closes #255

2023-11-20 04:23 UTC, lukehb commented on SFU/README.md
> +| rtcMazPort | Number | 49999 | Maximum RTC port for ICE, DTLS, RTP, etc. |
Should be `rtcMaxPort`

2023-11-20 04:24 UTC, lukehb commented on SFU/README.md
> +| SFUId | String | 'SFU' | The streamer name this peer will be given when connecting to the signalling server. Peers wishing to receive from this SFU should subscribe to this ID. |
I think 

> The ~~streamer~~ name this peer will be given when connecting to the signalling server. Peers wishing to receive from this SFU should subscribe to this ID.

2023-11-20 04:26 UTC, lukehb commented on SFU/README.md
> +This tells the pixel streaming plugin to stream simulcast with 3 streams, each one scaling down by 2. The sequence of values is as follows, `scale_down_factor,min_bitrate,max_bitrate,...repeating for
I prefer:

> scaling video resolution by half.

2023-11-20 04:43 UTC, lukehb commented on SFU/README.md
> +This tells the pixel streaming plugin to stream simulcast with 3 streams, each one scaling down by 2. The sequence of values is as follows, `scale_down_factor,min_bitrate,max_bitrate,...repeating for
> pixel streaming

to 

> Pixel Streaming

2023-11-20 04:45 UTC, lukehb requested changes
Minor changes requested.

2023-11-20 05:05 UTC, DenisTensorWorks reviewed
Minor style and sentence flow edits.

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +The SFU (Selective Forwarding Unit) is a mechanism to allow distributing a single stream out to a large number of peers. This is useful because when peers connect directly to the streamer, resources
> This means resources can quickly be drained

This means the resources can be quickly drained

> reencode the stream

re-encode the stream

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| subscribeStreamerId | String | 'DefaultStreamer' | This is the name of the streamer that this SFU should subscribe to and restream. |
> subscribe to and restream

subscribe to and re-stream

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| mediasoup | Object | | Mediasoup related configuration options. See below. |
> Mediasoup related

Mediasoup-related

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +### Mediasoup related configuration options.
> Mediasoup related configuration options.

Mediasoup-related configuration options

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| worker | Object | | Worker related configuration options. See below. |
> Worker related 

Worker-related

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| router | Object | | Router related configuration options. See below. |
> Router related 

Router-related

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| webRtcTransport | Object | | WebRTC transport related configuration options. See below. |
> transport related

transport-related

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +### Worker related configuration options.
> Worker related configuration options.

Worker-related configuration options

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +### Router related configuration options.
> Router related configuration options.

Router-related configuration options

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +### WebRTC transport related configuration options.
> WebRTC transport related configuration options.

WebRTC transport-related configuration options

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +| initialAvailableOutgoingBitrate | Number | Initial available outgoing bitrate (in bps). |
> (in bps).

(in bps/bits per second)

2023-11-20 05:05 UTC, DenisTensorWorks commented on SFU/README.md
> +When this streams to the SFU the SFU will detect these 3 streams and then selectively stream these out to connected peers based on their connection quality.
> When this streams to the SFU the SFU will detect

When this streams to the SFU, the SFU will detect

2023-11-20 05:05 UTC, DenisTensorWorks commented on SignallingWebServer/README.md
> +The signalling server is a small middle-man application that sits between streamers and other peers. It handles the initial connection negotiations and some other small ongoing control messages betwe
> a small middle-man application

a small intermediary application

2023-11-20 05:05 UTC, DenisTensorWorks commented on SignallingWebServer/README.md
> +Configuration of the signalling server is handled via the config.js file in the SignallingWebServer directory. The following are supported options.
> The following are supported options.

The following are its supported options.

2023-11-20 05:05 UTC, DenisTensorWorks commented on SignallingWebServer/README.md
> +| MatchmakerAddress | String | | The IP/hostname of the match maker application. |
> the match maker application

the matchmaker application

2023-11-20 05:05 UTC, DenisTensorWorks commented on SignallingWebServer/README.md
> +| MatchmakerPort | Number | 9999 | The port the match maker is listening on. |
> the match maker is listening on

the matchmaker is listening on

2023-11-20 05:05 UTC, DenisTensorWorks commented on SignallingWebServer/README.md
> +| PublicIp | String | "localhost" | The public IP/hostname of the host that the signalling server is listening on. This is used by the match maker. |
> This is used by the match maker.

This is used by the matchmaker.

2023-11-21 00:43 UTC, merged