Common library and Signalling Tester
EpicGames/PixelStreamingInfrastructure-archived-2024 pull request #473
Opened 2024-01-23 03:20 UTC by mcottontensor

## Relevant components:
- [x] Common library [NEW]
- [x] Signalling server
- [x] Frontend library
- [ ] Frontend UI library
- [ ] Matchmaker
- [x] Platform scripts
- [ ] SFU

## Problem statement:
There are a bunch of code in the front end library that can be useful for other users. Without a common library the other components need to copy/paste or implement their own etc.

## Solution
A few common implementations are extracted into a standalone Common library. This allows implementers to link with this library and write their own frontend application.
Additionally a protobuf description for signalling messages has been added. This isn't being used by any of the existing functionality yet, but should be possible to bring this in in the future.
A new tool has also been added under SS_Test. This is the signalling protocol tester. This is a small test application which can test the validity of the signalling protocol between signalling server and streamers and peers.
This tool comes with a github action that will run on changes to several components and fail if anything in the protocol changes to break existing behaviour.

## Documentation

## Test Plan and Compatibility

2024-01-24 03:54 UTC, lukehb commented on .github/workflows/publish-common-library-to-npm.yml
> +    branches: ['UE5.4']
Based on our discussion, this trigger needs to be on the UE5.5 branch now.

2024-01-24 04:45 UTC, lukehb requested changes
Left some comments to address before landing, hmu for any as needed. Good work on this PR!

2024-01-24 04:45 UTC, lukehb commented on .github/workflows/run-library-unit-tests.yml
>          node-version: '16.x'
This should be node 18.17.0 to match the other instance of us using NodeJS.

2024-01-24 04:45 UTC, lukehb commented on .github/workflows/run-signalling-tests.yml
> +        up-flags: "--build --abort-on-container-exit --exit-code-from tester"
This looks great!

2024-01-24 04:45 UTC, lukehb commented on Common/.gitignore
> +docs/
Why ignore `docs/` ?

2024-01-24 04:45 UTC, lukehb commented on Common/README.md
> +`npm i @epicgames-ps/lib-pixelstreamingcommon-ue5.4`
-ue5.5 suffix instead.

2024-01-24 04:45 UTC, lukehb commented on Common/package.json
> +    "name": "@epicgames-ps/lib-pixelstreamingcommon-ue5.4",
-ue5.5

2024-01-24 04:45 UTC, lukehb commented on Common/package.json
> +    "description": "Common utilities library for Unreal Engine 5.4 Pixel Streaming",
5.5

2024-01-24 04:45 UTC, lukehb commented on Common/protobuf/signalling_messages.proto
> +  peerConnectionOptions peerConnectionOptions = 2;
What do you think about adding an optional signalling protocol version field here? I think this will be helpful going forward.

2024-01-24 04:45 UTC, lukehb commented on Common/protobuf/signalling_messages.proto
> +  string id = 2;
I am also considering an optional version field here where the streamer can specify its version, wdyt?

2024-01-24 04:45 UTC, lukehb commented on Common/src/Logger/Logger.ts
> +        //console.log(`Level: ${level}\nMsg: ${message}\nCaller: ${stack}`);
I think it is totally reasonable to not log the stack trace for `Info` and `Warning` messages, but I think for `Error` messages then we should. Can you make this modification?

2024-01-24 04:45 UTC, lukehb commented on Common/src/Transport/ITransport.ts
> +export interface ITransport {
You wrote a good description of this interface in the readme.md, can you also duplicate it here?

2024-01-24 04:45 UTC, lukehb commented on Common/src/WebSockets/MessageSend.ts
> -    payload: () => string;
The payload() method is removed from the public interface, we should document this in our PR notes and instruct users why/what to do different if they were using that method before.

2024-01-24 04:45 UTC, lukehb commented on Common/src/WebSockets/SignallingProtocol.ts
> +    transportEvents: EventTarget;
Do each of the transportEvents we report, e.g. `open`, `error`, `close` etc. have a unit test? If not, I think we could potentially skip seeing as we have the SS_Tester test anyway. Your thoughts?

2024-01-24 04:45 UTC, lukehb commented on Frontend/library/package.json
>          "build-dev": "npx webpack --config webpack.dev.js",
I think `build-dev` needs an update here too.

2024-01-24 04:45 UTC, lukehb commented on Frontend/library/src/PixelStreaming/PixelStreaming.ts
> -        return this._webRtcController.webSocketController;
Removing this public method from the API, I think the idea here is `signallingProtocol()` is a direct replacement for how the controller was used. If so we should mention this in our PR notes.

2024-01-24 04:45 UTC, lukehb commented on Frontend/library/src/WebSockets/WebSocketController.ts
> -    onConfig(messageConfig: MessageReceive.MessageConfig) {}
We remove this type from the public API in favour of signalling protocol, how would a downstream user now do custom handling of the `onConfig` message and so on.

I think this can be okay if we have events that are emitted for onConfig and others.

To my reading it seems these public functions were removed and the protocol messages are all bound within `WebRTCPlayerController`, which is fine, but we should also exposed events for those who need to do custom handling on these events.

2024-01-24 04:45 UTC, lukehb commented on Frontend/library/src/WebSockets/WebSocketController.ts
> -    onConfig(messageConfig: MessageReceive.MessageConfig) {}
I think the ` addMessageHandler(messageId: string, messageHandler: (msg: MessageReceive.MessageRecv) => void) ` in the signallingprotocol class is not enough to fulfil this presently either because it can only take a single event bound per message type. One way to allow custom handling would be to allow addMessageHandler to, under to hood, support having multiple observers bound per message type.

2024-01-24 04:45 UTC, lukehb commented on Frontend/library/src/WebSockets/WebSocketController.ts
> -    onConfig(messageConfig: MessageReceive.MessageConfig) {}
And ofc, this would then have to be documented in the PR notes.

2024-01-24 04:45 UTC, lukehb commented on SS_Test/src/index.ts
> +async function main(): Promise<void> {
Small comment here explaining in general terms what `main()` procedure will attempt to do.

2024-01-24 04:48 UTC, lukehb commented
I guess our main readme.md should also include an explanation for what is `common` and `SS_Tester`

2024-01-24 04:59 UTC, mcottontensor commented on Common/.gitignore
> +docs/
Hmm this file was copied directly from the frontend folder where its ignored there too.

2024-01-24 05:45 UTC, mcottontensor commented on Common/src/Logger/Logger.ts
> +        //console.log(`Level: ${level}\nMsg: ${message}\nCaller: ${stack}`);
Upon looking at it again... Why do we pass in the stacktrace at the callsite rather than just in the method itself? It would mean that the stack trace ends with the Logger function but the very next level will have the one we're looking for. I think its a decent tradeoff to having large verbose logging calls all over the codebase.

2024-01-24 05:49 UTC, mcottontensor commented on Common/src/WebSockets/MessageSend.ts
> -    payload: () => string;
It was moved into MessageSend with a common implementation. I believe it can still be overridden, no?

2024-01-25 00:37 UTC, mcottontensor commented on Frontend/library/src/WebSockets/WebSocketController.ts
> -    onConfig(messageConfig: MessageReceive.MessageConfig) {}
So I've made a change to the handlers so it now uses an EventEmitter that's exposed in SignallingProtocol so we can use that functionality to add/remove however many listeners we want.
I also moved the transport events to an EventEmitter too mostly to be consistent but also because it's just a nicer interface.

2024-01-25 00:46 UTC, mcottontensor commented on Common/src/WebSockets/SignallingProtocol.ts
> +    transportEvents: EventTarget;
I'm not sure what we would test? That they're fired when the websocket opens/closes/errors? That's working as it is and I don't see that part of the code changing a lot or even being very complex. I feel like adding unit tests to it would just add complexity.
The SS_Tester doesn't really touch that stuff at the moment.

2024-01-25 01:13 UTC, lukehb requested changes
Minor comments mostly about common's package.json

2024-01-25 01:13 UTC, lukehb commented on Common/package.json
> +        "webpack": "^5.75.0",
I don't think common uses webpack, jest, webxr. These can be removed.

2024-01-25 01:13 UTC, lukehb commented on Common/package.json
> +        "webpack": "^5.75.0",
Additionally, we can probably add a `lint` under the `scripts` section to match frontend.

2024-01-25 01:13 UTC, lukehb commented on Common/src/WebSockets/SignallingProtocol.ts
> +    messageHandlers: EventEmitter;
Nice

2024-01-28 23:20 UTC, lukehb commented on Common/src/WebSockets/SignallingProtocol.ts
> +    transportEvents: EventTarget;
Fair, it is a bit like testing getter and setter at that point I suppose.

2024-01-28 23:22 UTC, lukehb approved these changes

2024-01-28 23:29 UTC, merged